1. values added:  20
2. final result:  20
3. values added:  20
4. A `ReferenceError` is returned because `let` declares variables within the scope of its block. The variable `result` is called outside of its scope on line 13.
5. five
6. six